# Generated by Django 6.0.5 on 2026-05-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('country', models.CharField()),
                ('pincode', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.CharField()),
                ('totalpayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending')),
            ],
        ),
    ]
