# Generated by Django 6.0.5 on 2026-06-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0009_alter_order_email_alter_order_shipping_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='furni.order'),
        ),
    ]
