# Generated by Django 6.0.5 on 2026-06-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0011_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seller',
        ),
    ]
