# Generated by Django 6.0.5 on 2026-06-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0013_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='country',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='state',
        ),
    ]
