# Generated by Django 6.0.5 on 2026-06-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0014_remove_seller_address_remove_seller_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='mobile',
        ),
    ]
