# Generated by Django 6.0.5 on 2026-06-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0015_remove_seller_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='furni.seller'),
            preserve_default=False,
        ),
    ]
