# Generated by Django 6.0.5 on 2026-06-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0016_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
