# Generated by Django 6.0.5 on 2026-06-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0017_product_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default='surat', max_length=350),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(default='surat', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='country',
            field=models.CharField(default='india', max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='mobile',
            field=models.CharField(default=12, max_length=255),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(default='gujarat', max_length=255),
        ),
    ]
