# Generated by Django 6.0.5 on 2026-06-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furni', '0018_seller_address_seller_city_seller_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
